version: "3"
services:
  app:
    container_name: bossabox-mongo-node
    restart: always
    build: .
    ports:
      - "80:3000"
    links:
      - "mongo"
  mongo:
    container_name: bossabox
    image: mongo
    ports:
      - "27017:27017"
